import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import StyledComponentsRegistry from "./registry";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AppContextProvider } from "@/context/appContextProvider";
import NextTopLoader from "nextjs-toploader";
import "@smastrom/react-rating/style.css";
import "simplebar-react/dist/simplebar.min.css";
import { SocketContextProvider } from "@/context/socketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tutor Pedia",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AppContextProvider>
          <SocketContextProvider>
            <StyledComponentsRegistry>
              <NextTopLoader color="skyblue" height={4} showSpinner={false} />
              <div style={{ minHeight: "500px" }}>{children}</div>
            </StyledComponentsRegistry>
          </SocketContextProvider>
        </AppContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
};

export default RootLayout;
