import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/Header";
import StyledComponentsRegistry from "./registry";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ApolloWrapper } from "./gqlConfig/ApolloWrapper";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tutor Pedia",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ApolloWrapper>
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_API_ID ?? ""}>
          <StyledComponentsRegistry>
            <Header />
            <div style={{minHeight:"500px"}}>{children}</div>
            <Footer/>
          </StyledComponentsRegistry>
        </GoogleOAuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
